sudo: false

language: bash

services:
  - docker

before_install:
  - ls
  - ls /
  - echo $PWD
  #- docker pull tobsto/sqylab-ci
  #- docker run -v /home/travis/tobsto/testrepo:/mnt/sqylab tobsto/sqylab-ci /bin/bash -c "source ~/.profile; conda create -n sqylab; conda activate sqylab; conda install pip; ls /mnt/sqylab/; pip install -r /mnt/sqylab/requirements.txt; pytest"
